=== SoulexDev/Assembly-Engine/resources/ui/ASXML.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="https://thedevassembly.com"
		   xmlns="https://thedevassembly.com"
		   elementFormDefault="qualified">
	
	<!-- simple elements -->
	<xs:element name="text" type="xs:string"/>
	<xs:element name="layoutType" type="xs:string"/>
	<xs:element name="layoutInteraction" type="xs:string"/>
	<xs:element name="color" type="xs:string" default="#ffffffff"/>
	<xs:element name="image" type="xs:string"/>
	
	<!-- complex elements -->
	<xs:element name="ASXML" type="ASXML"/>
	<xs:element name="Group" type="Group"/>
	<!--<xs:element name="Image" type="Image"/>-->
	<xs:element name="RectTransform" type="RectTransform"/>
	<xs:element name="Vector2" type="Vector2"/>
	
	<!-- attribute groups -->
	<xs:attributeGroup name="integer-2">
		<xs:attribute name="x" type="xs:integer" />
		<xs:attribute name="y" type="xs:integer"/>
	</xs:attributeGroup>

	<xs:attributeGroup name="decimal-2">
		<xs:attribute name="x" type="xs:decimal" />
		<xs:attribute name="y" type="xs:decimal"/>
	</xs:attributeGroup>

	<!-- simple element definitions -->
	<xs:simpleType name="layoutType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="inherit"/>
			<xs:enumeration value="center-horizontal"/>
			<xs:enumeration value="center-vertical"/>
			<xs:enumeration value="top-horizontal"/>
			<xs:enumeration value="top-vertical"/>
			<xs:enumeration value="bottom-horizontal"/>
			<xs:enumeration value="bottom-vertical"/>
			<xs:enumeration value="right-horizontal"/>
			<xs:enumeration value="right-vertical"/>
			<xs:enumeration value="left-horizontal"/>
			<xs:enumeration value="left-vertical"/>
			<xs:enumeration value="top-right-horizontal"/>
			<xs:enumeration value="top-right-vertical"/>
			<xs:enumeration value="top-left-hotizontal"/>
			<xs:enumeration value="top-left-vertical"/>
			<xs:enumeration value="bottom-right-horizontal"/>
			<xs:enumeration value="bottom-right-vertical"/>
			<xs:enumeration value="bottom-left-hotizontal"/>
			<xs:enumeration value="bottom-left-vertical"/>
			<xs:enumeration value="fill-horizontal"/>
			<xs:enumeration value="fill-vertical"/>
			<xs:enumeration value="fill-horizontal-right"/>
			<xs:enumeration value="fill-vertical-right"/>
			<xs:enumeration value="fill-horizontal-left"/>
			<xs:enumeration value="fill-vertical-left"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="layoutInteraction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="fit"/>
			<xs:enumeration value="stack"/>
			<xs:enumeration value="stack-horizontal"/>
			<xs:enumeration value="stack-vertical"/>
			<xs:enumeration value="ignore"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="color">
		<xs:restriction base="xs:string">
			<xs:pattern value="[#][0-9a-fA-F]{9}"/>
			<xs:minLength value="9"/>
			<xs:maxLength value="9"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- complex element definitions -->
	<xs:complexType name="ASXML">
		<xs:sequence>
			<xs:element ref="Group" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Group">
		<xs:sequence>
			<xs:element ref="RectTransform" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="layoutInteraction" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="layoutType" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="color" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="image" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="Group" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="RectTransform">
		<xs:sequence>
			<xs:element name="position" type="Vector2I"/>
			<xs:element name="size" type="Vector2I"/>
			<xs:element name="anchor" type="Vector2"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Vector2I">
		<xs:attributeGroup ref="integer-2"/>
	</xs:complexType>

	<xs:complexType name="Vector2">
		<xs:attributeGroup ref="decimal-2"/>
	</xs:complexType>
	
</xs:schema>

=== SoulexDev/Assembly-Engine/resources/ui/ExampleUI.xml
<?xml version="1.0" encoding="utf-8" ?>
<ASXML
	xmlns="https://thedevassembly.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://thedevassembly.com ASXML.xsd">

	<Group id="root group">
		<position x="0" y="0"/>
		<size x="1920" y="1080"/>
		<anchor x="0" y="0"/>
		
		<layoutInteraction>ignore</layoutInteraction>
		<layoutType>none</layoutType>
		<color>#ffffffff</color>

		<Group id="test group">
			<position x="400" y="400"/>
			<size x="250" y="100"/>
			<anchor x="0" y="0"/>

			<layoutInteraction>ignore</layoutInteraction>
			<layoutType>center-horizontal</layoutType>
			<color>#ffffffff</color>
			
			<Group id="baby group 1">
				<position x="960" y="540"/>
				<size x="200" y="200"/>
				<anchor x="0.5" y="0.5"/>

				<layoutInteraction>ignore</layoutInteraction>
				<layoutType>inherit</layoutType>
				<color>#ffffffff</color>
				<image>textures/brick_medieval.jpg</image>
			</Group>
			<Group id="baby group 2">
				<position x="960" y="540"/>
				<size x="200" y="125"/>
				<anchor x="0.5" y="0.5"/>

				<layoutInteraction>ignore</layoutInteraction>
				<layoutType>inherit</layoutType>
				<color>#ffffffff</color>
				<image>textures/Prototype_Dark.png</image>
			</Group>
			<Group id="baby group 3">
				<position x="960" y="540"/>
				<size x="50" y="250"/>
				<anchor x="0.5" y="0.5"/>

				<layoutInteraction>ignore</layoutInteraction>
				<layoutType>inherit</layoutType>
				<color>#ffffffff</color>
				<image>textures/grass_seamless.jpg</image>
			</Group>
		</Group>
	</Group>
</ASXML>
