=== SoulexDev/Assembly-Engine/UI/ASXML.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="https://thedevassembly.com"
		   xmlns="https://thedevassembly.com"
		   elementFormDefault="qualified">
	
	<!-- simple elements -->
	<xs:element name="text" type="xs:string"/>
	<xs:element name="layoutType" type="xs:string"/>
	<xs:element name="layoutInteraction" type="xs:string"/>
	<xs:element name="anchor-x" type="xs:decimal"/>
	<xs:element name="anchor-y" type="xs:decimal"/>
	<xs:element name="color" type="xs:hexBinary" default="FFFFFFFF"/>
	
	<!-- complex elements -->
	<xs:element name="ASXML" type="ASXML"/>
	<xs:element name="Group" type="Group"/>
	<xs:element name="Image" type="Image"/>
	
	<!-- groups -->
	<xs:group name="transform">
		<xs:sequence>
			<xs:element name="x" type="xs:integer"/>
			<xs:element name="y" type="xs:integer"/>
			<xs:element name="width" type="xs:integer"/>
			<xs:element name="height" type="xs:integer"/>
			<xs:element ref="anchor-x"/>
			<xs:element ref="anchor-y"/>
		</xs:sequence>
	</xs:group>

	<!-- simple element definitions -->
	<xs:simpleType name="layoutType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="inherit"/>
			<xs:enumeration value="center-horizontal"/>
			<xs:enumeration value="center-vertical"/>
			<xs:enumeration value="top-horizontal"/>
			<xs:enumeration value="top-vertical"/>
			<xs:enumeration value="bottom-horizontal"/>
			<xs:enumeration value="bottom-vertical"/>
			<xs:enumeration value="right-horizontal"/>
			<xs:enumeration value="right-vertical"/>
			<xs:enumeration value="left-horizontal"/>
			<xs:enumeration value="left-vertical"/>
			<xs:enumeration value="top-right-horizontal"/>
			<xs:enumeration value="top-right-vertical"/>
			<xs:enumeration value="top-left-hotizontal"/>
			<xs:enumeration value="top-left-vertical"/>
			<xs:enumeration value="bottom-right-horizontal"/>
			<xs:enumeration value="bottom-right-vertical"/>
			<xs:enumeration value="bottom-left-hotizontal"/>
			<xs:enumeration value="bottom-left-vertical"/>
			<xs:enumeration value="fill-horizontal"/>
			<xs:enumeration value="fill-vertical"/>
			<xs:enumeration value="fill-horizontal-right"/>
			<xs:enumeration value="fill-vertical-right"/>
			<xs:enumeration value="fill-horizontal-left"/>
			<xs:enumeration value="fill-vertical-left"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="layoutInteraction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="fit"/>
			<xs:enumeration value="stack"/>
			<xs:enumeration value="stack-horizontal"/>
			<xs:enumeration value="stack-vertical"/>
			<xs:enumeration value="ignore"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="anchor-x">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="anchor-y">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- complex element definitions -->
	<xs:complexType name="ASXML">
		<xs:sequence>
			<xs:element name="Group" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Group">
		<xs:sequence>
			<xs:element ref="layoutType" minOccurs="1" maxOccurs="1"/>
			<xs:group ref="transform" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="Group" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="Image" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="color" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Image">
		<xs:sequence>
			<xs:element ref="layoutInteraction" minOccurs="1" maxOccurs="1"/>
			<xs:group ref="transform" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="color" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="assetpath" type="xs:string" use="optional"/>
	</xs:complexType>
	
</xs:schema>

=== SoulexDev/Assembly-Engine/UI/ExampleUI.xml
<?xml version="1.0" encoding="utf-8" ?>
<ASXML
	xmlns="https://thedevassembly.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://thedevassembly.com ASXML.xsd">

	<Group>
		<layoutType>center</layoutType>
		<x>0</x>
		<y>0</y>
		<width>1920</width>
		<height>1080</height>
		<anchor-x>0</anchor-x>
		<anchor-y>0</anchor-y>
		<Image assetpath="textures/creepfur.png">
			<layoutInteraction>ignore</layoutInteraction>
			<x>20</x>
			<y>-20</y>
			<width>100</width>
			<height>100</height>
			<anchor-x>0</anchor-x>
			<anchor-y>1</anchor-y>
			<color>FF0000FF</color>
		</Image>
	</Group>
</ASXML>
